### ISSUE TITLE
[Question] How to use pullItemRemote compared to pullItem

### ISSUE THREAD

**Issue by adriengou** [SquidDev-CC/CC-Tweaks#141]
Hello,
so i looked the in-game documentation to show the method for the pullItemRemote function. The first arguments needed is explained as "remote name". Can someone please explain what is this remote name ? Is it the name given by a wired modem, cause i tried to use the command like this
"c.pullItemRemote("chest_1",1) and it says "other inventory not found".
Thanks in advance for your help, i love your mod :) .
This is my setup: http://imgur.com/a/OOKWW

**Comment by SquidDev** [comment]
Yeah, it should be the name given by the wired modem. Can you post an image of your current setup: just so I can see what everything is connected to?

**Comment by adriengou** [comment]
This is my setup: http://imgur.com/a/OOKWW

**Comment by SquidDev** [comment]
Right, this appears to be a bug, though rebinding the modem (by right clicking twice) or relogging appears to fix it. 

I'll have a look to see what I can do. I'm not really maintaining the 1.7.10 branch so I'll see. Thanks for the report!

**Comment by SquidDev** [comment]
Right, this appears to be fixed in 1.8.9+ due to [this commit](https://github.com/SquidDev-CC/CCTweaks/commit/c3ebfba09239617e86c499e255591f154cdaf4de). I suspect this is another incarnation of #92.

I'm not going to backport this fix as I have no wish to maintain the 1.7.10 version of the mod. You may have some luck with [Lur's fork](https://github.com/lurquhar1221/CCTweaks) for 1.7.10 though I can't find a download anywhere. I've sent them a message and I'll post a link here when I here back from him. 

Sorry about this 😦.

**Comment by SquidDev** [comment]
[Here](https://github.com/lurquhar1221/CCTweaks/releases/tag/v1.7.10-1.1.2)
