### ISSUE TITLE
API Implementation

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#23]
The current API includes too much code and ideally would be 90% interfaces with a small amount of logic. I think the easiest way to handle this would be for classes such as `NetworkRegistry` and `NetworkVisitor` to declare interfaces in the API and then have a loader such as [AE uses](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/api/java/appeng/api/AEApi.java) to load the relevant classes. These could be set with:
 - Field get via reflection
 - Class construction via reflection
 - Field set in main CCTweaks mod

## Network Registry
The `INetworkRegistry` interface should provide the following methods:
 - `addNodeProvider(INetworkNodeProvider)`
 - `isNode(IWorldAccess world, int x, int y, int z)`
 - `getNode(IWorldAccess world, int x, int y, int z)`. 

We could also add `IWorldPosition` and `TileEntity` equivalents (this applies to all methods that take a world position`

## Network visitor
I think the `INetworkVisitor` interface should provide an `Iterable<ISearchLoc>` instead (`Iterable<ISearchLoc> visitNetwork(...)`). This would mean instead of having to create custom visitor instances we can use a for each. 

We should also offer an optional `Set<ISearchLoc>` visited field as well as `IWorldPosition` and `TileEntity` equivalents. A method that can take multiple `IWorldPosition`s or tile entities would be useful to prevent having to manually create the visited field - you can then do `visitNetwork(binding.getPositions())`.

## NetworkHelpers
I'm really unsure how to do this. We could just not package it at all - they are all fairly trivial implementations. We could just handle it the same as the other items, or include it in another interface.

## Peripheral Network access (#17)
I think we're going for an `INetworkedComputerAccess` interface. This will extend `IComputerAccess` , and provide these additional methods:
 - `Iterable<ISearchLoc> getNodes()`. See network visitor.
 - `invalidateNetwork` Invalidates the network - like `NetworkHelpers.fireNetworkInvalidate`.
 - `Map<String, IPeripheral> getAttachedPeripherals()` I don't know if we want to lazy load this, or eager load it, or have a method that states if it is required or not. I don't even know if we want to cache it or not.
 - `sendPacket(Packet packet)` Sends a packet through the network.

The peripheral will need to implement `INetworkedPeripheral`. This will provide the  `attachToNetwork(INetworkedComputerAccess computer)` method, and the detach equivalent. This will be called *after* `attach` and *before* `detach`. Or instead of. Of the other way round. We might also want to add a `networkInvalidated` method to be called when its node is invalidated. I don't want to just duplicate `INetworkNode` though.

We're going to have to give some thought into registering custom providers. Probably talk about this in #17.

Any thoughts on this massive wall of text?

**Comment by ElvishJerricco** [comment]
Why wouldn't we just have a static field for the various APIs that gets set in the mod's initialization stage?

As for network access, I've realized the initial impulse to tie peripheral network access to the host computer was wrong. The IComputerAccess, I've found, serves a different purpose than we would want for the network access. INetworkAccess should just be its own interface, because the network its on has no relation to any computer.

In fact, the native peripheral API doesn't even know that remote peripherals exist. Its the Lua wrapper that includes detected remote peripherals using wired modems' remote peripheral methods. Computers get information about networks from the modem peripherals attached. Those modems get the information from the network, essentially just acting like a relay that the Lua wrapper uses.

The implication of this is that network access is limited to the cable network attached, rather than the entire host computer's network (as that computer might be attached to several networks). All in all, I think that's good.

I'll discuss solutions for this on the #17 page.

**Comment by ElvishJerricco** [comment]
Overall though, I think that most of this issue this is a housecleaning job that we might want to hold off on until the rest of the Networks milestone is completed.

**Comment by SquidDev** [comment]
I know most of this is just tidying stuff up, I'm just writing this now whilst it is in my head. I guess this is meant to be a bit of a RFC - if CCTransport is going to be using this I want to make sure that it is usable. I think you're right about `INetworkAccess` being a separate interface.

We could either use a private static field or a public final static field, either would be usable. I'm not that fussed about other mods changing it - reflection exists so they could if they really wanted. I'd prefer using construction rather than a field get, though I'd have to have a look at how other mods do it.

**Comment by SquidDev** [comment]
Closed in #29
