### ISSUE TITLE
Visitor visits every side

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#28]
The visitor currently visits every side that is connected on the node. This means that a packet can be received more than once on a network - as well as we scan peripherals multiple times on one node and we call `networkInvalidated` multiple times.

An alternative would be instead of testing for equality by checking the side we should test if this node isn't null and if it hasn't been visited already. This might require a rewrite of bits of the visitor though so should be fixed after [`feature/api-rewrites`](https://github.com/SquidDev-CC/CC-Tweaks/tree/feature/api-rewrites) is merged.

**Comment by ElvishJerricco** [comment]
I must be missing something. Where does it add visited nodes to the ```visited``` set?

**Comment by SquidDev** [comment]
In the `enqueue` method. It is something like `if(visited.add(location))`.

**Comment by ElvishJerricco** [comment]
There we go, [found it](https://github.com/SquidDev-CC/CC-Tweaks/blob/5d28a09c858d863ed9a568cff10806c632b92957/src/main/java/org/squiddev/cctweaks/core/network/visitor/NetworkVisitorIterator.java#L64). Anyway, the issue now is that we're adding every location to the ```visited``` set, regardless of whether it can be visited or not. So if we try to visit a node through a cover, it gets added to ```visited```, but doesn't get visited because of the cover. Then we don't try to visit it again from any other direction.

**Comment by SquidDev** [comment]
Yeah. You're right there. The thing is I want to ideally avoid fetching the node multiple times as the slowest bit will be running through the node providers. However storing the direction in the search location also doesn't work as otherwise we cannot find it.

**Comment by ElvishJerricco** [comment]
I think we just have to only add a node to ```visited``` when we actually visit it.
